// List of pigs from "m" to "z"

const pigsMZ = [

    {
        "id": "79",
        "name": "Malhado de Alcoba\u00e7a",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "80",
        "name": "Mangalitsa",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "81",
        "name": "Meishan",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "82",
        "name": "Middle White",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "83",
        "name": "Minzhu",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "84",
        "name": "Minokawa Buta",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "85",
        "name": "Mong Cai",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "86",
        "name": "Mora Romagnola",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "87",
        "name": "Moura",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "88",
        "name": "Mukota",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "89",
        "name": "Mulefoot",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "90",
        "name": "Myrhorod",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "91",
        "name": "Nero dei Nebrodi",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "92",
        "name": "Neijiang",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "93",
        "name": "Ningxiang",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "94",
        "name": "North Caucasian",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "95",
        "name": "North Siberian",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "96",
        "name": "Norwegian Landrace",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "97",
        "name": "Norwegian Yorkshire",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "98",
        "name": "Ossabaw Island",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "99",
        "name": "Oxford Sandy and Black",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "100",
        "name": "Philippine Native",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "101",
        "name": "Pi\u00e9train",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "102",
        "name": "Poland China",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "103",
        "name": "Red Wattle",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "104",
        "name": "Semirechensk",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "105",
        "name": "Siberian Black Pied",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "106",
        "name": "Small Black",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "107",
        "name": "Small White",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "108",
        "name": "Spots",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "109",
        "name": "Surabaya Babi",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "110",
        "name": "Swabian-Hall",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "111",
        "name": "Swedish Landrace",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "112",
        "name": "Taihu pig",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "113",
        "name": "Tamworth",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "114",
        "name": "Thuoc Nhieu",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "115",
        "name": "Tibetan",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "116",
        "name": "Tokyo-X",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "117",
        "name": "Tsivilsk",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "118",
        "name": "Turopolje",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "119",
        "name": "Ukrainian Spotted Steppe",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "120",
        "name": "Ukrainian White Steppe",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "121",
        "name": "Urzhum",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "122",
        "name": "Vietnamese Potbelly",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "123",
        "name": "Welsh",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "124",
        "name": "Wessex Saddleback",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "125",
        "name": "West French White",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "126",
        "name": "Windsnyer",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "127",
        "name": "Wuzishan",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "128",
        "name": "Yanan",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    },
    {
        "id": "129",
        "name": "Yorkshire Blue and White",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pig_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 21:11:10"
    }
];

export { pigsMZ };
