// List of domestic dogs from "o" to "r"

const dogsOR = [
    {
        "id": "115",
        "name": "Old English Sheepdog",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:48:15"
    },
    {
        "id": "116",
        "name": "Otterhound",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:48:15"
    },
    {
        "id": "315",
        "name": "Olde English Bulldogge",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 08:56:10"
    },
    {
        "id": "117",
        "name": "Papillon",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:48:15"
    },
    {
        "id": "118",
        "name": "Pekingese",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:48:15"
    },
    {
        "id": "119",
        "name": "Pembroke Welsh Corgi",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:48:15"
    },
    {
        "id": "120",
        "name": "Petit Basset Griffon Vendeen",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:48:15"
    },
    {
        "id": "121",
        "name": "Pharaoh Hound",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:48:15"
    },
    {
        "id": "122",
        "name": "Pointer",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:48:15"
    },
    {
        "id": "123",
        "name": "Pomeranian",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:48:15"
    },
    {
        "id": "124",
        "name": "Poodle (Miniature)",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:48:15"
    },
    {
        "id": "125",
        "name": "Poodle (Standard)",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:48:15"
    },
    {
        "id": "126",
        "name": "Poodle (Toy)",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:48:15"
    },
    {
        "id": "127",
        "name": "Portuguese Water Dog",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:48:15"
    },
    {
        "id": "128",
        "name": "Pug",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:48:15"
    },
    {
        "id": "129",
        "name": "Puli",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:48:15"
    },
    {
        "id": "316",
        "name": "Polish Hunting Dog",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 08:56:10"
    },
    {
        "id": "317",
        "name": "Pakistani Mastiff",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 08:56:10"
    },
    {
        "id": "318",
        "name": "Patterdale Terrier",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 08:56:10"
    },
    {
        "id": "319",
        "name": "Parson Russell Terrier",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 08:56:10"
    },
    {
        "id": "320",
        "name": "Perro de Presa Canario",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 08:56:10"
    },
    {
        "id": "321",
        "name": "Perro de Presa Mallorquin",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 08:56:10"
    },
    {
        "id": "322",
        "name": "Peruvian Inca Orchid",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 08:56:10"
    },
    {
        "id": "323",
        "name": "Picardy Spaniel",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 08:56:10"
    },
    {
        "id": "324",
        "name": "Plott Hound",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 08:56:10"
    },
    {
        "id": "325",
        "name": "Plummer Terrier",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 08:56:10"
    },
    {
        "id": "326",
        "name": "Polish Lowland Sheepdog",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 08:56:10"
    },
    {
        "id": "327",
        "name": "Portuguese Podengo",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 08:56:10"
    },
    {
        "id": "328",
        "name": "Prazsky Krysarik",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 08:56:10"
    },
    {
        "id": "329",
        "name": "Pudelpointer",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 08:56:10"
    },
    {
        "id": "330",
        "name": "Pyrenean Shepherd",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 08:56:10"
    },
    {
        "id": "331",
        "name": "Pont-Audemer Spaniel",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 08:56:10"
    },
    {
        "id": "130",
        "name": "Rhodesian Ridgeback",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:48:15"
    },
    {
        "id": "131",
        "name": "Rottweiler",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:48:15"
    },
    {
        "id": "332",
        "name": "Rafeiro do Alentejo",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 09:30:59"
    },
    {
        "id": "333",
        "name": "Rajapalyam dog",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 09:30:59"
    },
    {
        "id": "334",
        "name": "Rat Terrier",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 09:30:59"
    },
    {
        "id": "335",
        "name": "Redbone Coonhound",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 09:30:59"
    },
    {
        "id": "336",
        "name": "Russian Spaniel",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 09:30:59"
    },
    {
        "id": "337",
        "name": "Russian Toy",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 09:30:59"
    },
    {
        "id": "339",
        "name": "Rough Collie",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-07 09:30:59"
    },
];

export { dogsOR };