// List of domestic dogs for "a"

const dogsA = [
    {
        "id": "178",
        "name": "Australian Kelpie",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:02"
    },
    {
        "id": "181",
        "name": "Austrian Black and Tan Hound",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:02"
    },
    {
        "id": "182",
        "name": "Austrian Pinscher",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:02"
    },
    {
        "id": "183",
        "name": "Azawakh",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:02"
    },
    {
        "id": "186",
        "name": "Andalusian Hound",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:02"
    },
    {
        "id": "193",
        "name": "Alaskan Klee Kai",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:15"
    },
    {
        "id": "194",
        "name": "American Pit Bull Terrier",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:15"
    },
    {
        "id": "195",
        "name": "American Staghound",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:15"
    },
    {
        "id": "196",
        "name": "American White Shepherd",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:15"
    },
    {
        "id": "197",
        "name": "Appenzeller Sennenhund",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:15"
    },
    {
        "id": "199",
        "name": "Ariege Pointer",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:15"
    },
    {
        "id": "200",
        "name": "Ariegeois",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:15"
    },
    {
        "id": "201",
        "name": "Australian Bulldog",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:15"
    },
    {
        "id": "203",
        "name": "Australian Silky Terrier",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:15"
    },
    {
        "id": "204",
        "name": "Australian Stumpy Tail Cattle Dog",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:15"
    },
    {
        "id": "208",
        "name": "Alopekis",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:15"
    },
    {
        "id": "209",
        "name": "American Bulldog",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:15"
    }, {
        "id": "1",
        "name": "Afghan Hound",
        "weight_1": "20",
        "weight_2": "34",
        "height_1": "24",
        "height_2": "29",
        "dog_function": "Hunting",
        "other_name": "Spay, Sage Balochi, Ogar Afgan, Eastern Greyhound Persian",
        "color": "black, cream, red",
        "location": "Afghanistan, Iran, Pakistan",
        "animal_group": "Hound Hypoallergenic",
        "offsprings": "0",
        "life_span": "14",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 12:38:33"
    },
    {
        "id": "2",
        "name": "Airedale Terier",
        "weight_1": "40",
        "weight_2": "65",
        "height_1": "22",
        "height_2": "24",
        "dog_function": "Hunting",
        "other_name": "Waterside Bingley Irish Red Terrier",
        "color": "borziboying again",
        "location": "United Kingdom",
        "animal_group": "Terrier dog breeds (AKC)",
        "offsprings": "0",
        "life_span": "13",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 14:45:36"
    },
    {
        "id": "3",
        "name": "akita",
        "weight_1": "32",
        "weight_2": "58",
        "height_1": "24",
        "height_2": "28",
        "dog_function": "Guard",
        "other_name": "Akita Inu, Japanese Akita, American Akita",
        "color": "Fawn, Brindle, Red, White, Pinto",
        "location": "Japan",
        "animal_group": "Working dog breeds (AKC)",
        "offsprings": "4",
        "life_span": "15",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 14:45:36"
    },
    {
        "id": "5",
        "name": "American Cocker Spaniel",
        "weight_1": "7",
        "weight_2": "14",
        "height_1": "14",
        "height_2": "16",
        "dog_function": "Sport",
        "other_name": "Cocker Spaniel",
        "color": "Black, Red, Tan, Silver, Brown, Tri-color, White & Buff",
        "location": "United States of America",
        "animal_group": "Sporting dog breeds (AKC)",
        "offsprings": "5",
        "life_span": "15",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 14:48:53"
    },
    {
        "id": "6",
        "name": "American Eskimo Dog (Miniature)",
        "weight_1": "10",
        "weight_2": "19",
        "height_1": "15",
        "height_2": "19",
        "dog_function": "companion, performer",
        "other_name": "Eskimo Spitz, American Spitz, German Spitz, Eskie",
        "color": "White, Biscuit",
        "location": "Germany",
        "animal_group": "Non-sporting dog breeds (AKC)",
        "offsprings": "2",
        "life_span": "15",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 14:48:53"
    },
    {
        "id": "7",
        "name": "American Eskimo Dog (Standard)",
        "weight_1": "10",
        "weight_2": "19",
        "height_1": "12",
        "height_2": "15",
        "dog_function": "companion, performer",
        "other_name": "Eskimo Spitz, American Spitz, German Spitz, Eskie",
        "color": "White, Biscuit",
        "location": "Germany",
        "animal_group": "Non-sporting dog breeds (AKC)",
        "offsprings": "2",
        "life_span": "15",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 14:48:53"
    },
    {
        "id": "8",
        "name": "American Eskimo Dog (Toy)",
        "weight_1": "8",
        "weight_2": "10",
        "height_1": "9",
        "height_2": "12",
        "dog_function": "companion, performer",
        "other_name": "Eskimo American German Spitz, Eskie",
        "color": "White, Biscuit",
        "location": "Germany",
        "animal_group": "Non-sporting dog breeds (AKC)",
        "offsprings": "2",
        "life_span": "15",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 14:48:53"
    },
    {
        "id": "9",
        "name": "American Foxhound",
        "weight_1": "20",
        "weight_2": "24",
        "height_1": "21",
        "height_2": "25",
        "dog_function": "Hunting",
        "other_name": "Foxhound",
        "color": "Red, Tan, Blue, White, Tri-color, White & Cream",
        "location": "United States",
        "animal_group": "Hound dog breeds (AKC)",
        "offsprings": "7",
        "life_span": "12",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 14:48:53"
    },
    {
        "id": "10",
        "name": "American Staffordshire Terrier",
        "weight_1": "61",
        "weight_2": "88",
        "height_1": "17",
        "height_2": "19",
        "dog_function": "Guard",
        "other_name": "AmStaff",
        "color": "Fawn, Brindle, Black, Blue, Brown, Sable",
        "location": "United States",
        "animal_group": "Terrier dog breeds (AKC)",
        "offsprings": "4",
        "life_span": "12",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 14:48:53"
    },
    {
        "id": "11",
        "name": "American Water Spaniel",
        "weight_1": "25",
        "weight_2": "40",
        "height_1": "15",
        "height_2": "18",
        "dog_function": "Sport",
        "other_name": "AWS, American Brown Spaniel, American Brown Water Spaniel",
        "color": "Liver, Brown, Chocolate",
        "location": "United States",
        "animal_group": "Sporting dog breeds (AKC)",
        "offsprings": "4",
        "life_span": "15",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 14:48:53"
    },
    {
        "id": "12",
        "name": "Anatolian Shepherd",
        "weight_1": "40",
        "weight_2": "65",
        "height_1": "28",
        "height_2": "32",
        "dog_function": "Guard",
        "other_name": "Kham Kepiji dogs, Karabash in dogs, Scandinavian Nygaard dogs",
        "color": "Liver, Brindle, Blue Fawn, White, Red Fawn, White & Biscuit",
        "location": "Turkey",
        "animal_group": "Working dog breeds (AKC)",
        "offsprings": "4",
        "life_span": "15",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 14:48:53"
    },
    {
        "id": "13",
        "name": "Australian Cattle Dog",
        "weight_1": "35",
        "weight_2": "45",
        "height_1": "17",
        "height_2": "20",
        "dog_function": "livestock, herding",
        "other_name": "ACD, Cattle Dog, Blue Red Queensland Heeler",
        "color": "Blue, blue red mottled, blue red speckled",
        "location": "Australia",
        "animal_group": "Herding dog breeds (AKC)",
        "offsprings": "3",
        "life_span": "15",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 14:48:53"
    },
    {
        "id": "14",
        "name": "Alaskan Malamute",
        "weight_1": "32",
        "weight_2": "43",
        "height_1": "22",
        "height_2": "26",
        "dog_function": "Working",
        "other_name": "Mal or Mally",
        "color": "Black & White, Brown & White, Red & White, Gray & White, Seal & White, Sable & White",
        "location": "United States (Alaska)",
        "animal_group": "Working dog breeds (AKC)",
        "offsprings": "0",
        "life_span": "16",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 14:49:07"
    },
    {
        "id": "24",
        "name": "Australian Shepherd",
        "weight_1": "40",
        "weight_2": "65",
        "height_1": "18",
        "height_2": "23",
        "dog_function": "sheep herding",
        "other_name": "Aussie or little blue dog",
        "color": "Black, Red, Red Merle, Blue Merle, Black tricolor, Red tricolor, Merle",
        "location": "United States",
        "animal_group": "Herding dog breeds (AKC)",
        "offsprings": "4",
        "life_span": "15",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 15:08:50"
    },
    {
        "id": "25",
        "name": "Australian Terrier",
        "weight_1": "12",
        "weight_2": "14",
        "height_1": "9",
        "height_2": "11",
        "dog_function": "killing small vermin",
        "other_name": "Aussie",
        "color": "Red, Sand, Blue ,Tan",
        "location": "Australia",
        "animal_group": "Terrier dog breeds (UKC)",
        "offsprings": "3",
        "life_span": "15",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 15:08:50"
    }, {
        "id": "163",
        "name": "Affenpinscher",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "www.petfinder.com, www.dogbreedslist.info",
        "edited_date": "2015-05-06 20:26:02"
    },
    {
        "id": "164",
        "name": "Africanis",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:02"
    },
    {
        "id": "165",
        "name": "Aidi",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:02"
    },
    {
        "id": "166",
        "name": "Akbash Dog",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:02"
    },
    {
        "id": "167",
        "name": "Alano Espanol",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:02"
    },
    {
        "id": "168",
        "name": "Alapaha Blue Blood Bulldog",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:02"
    },
    {
        "id": "174",
        "name": "Argentine Dogo",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 20:26:02"
    }
]

export { dogsA };