// List of domestic dogs for "b"

const dogsB = [
    {
        "id": "26",
        "name": "Basenji",
        "weight_1": "22",
        "weight_2": "24",
        "height_1": "15",
        "height_2": "16",
        "dog_function": "hunting small game",
        "other_name": "African Bush African Barkless Congo Zande Dog",
        "color": "Black, Tan, Brindle, Red, Black & White, Tri-color",
        "location": "Republic Democratic of Congo",
        "animal_group": "Hound dog breeds (AKC)",
        "offsprings": "4",
        "life_span": "16",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 15:08:50"
    },
    {
        "id": "27",
        "name": "Basset Hound",
        "weight_1": "45",
        "weight_2": "75",
        "height_1": "11",
        "height_2": "15",
        "dog_function": "trailing rabbits and hare",
        "other_name": "Basset, Hush Puppy",
        "color": "Black & White, Brown & White, Red & White, Tri-color, Lemon & White, Black & Brown",
        "location": "Great Britain, United Kingdom, France",
        "animal_group": "Hound dog breeds (AKC)",
        "offsprings": "4",
        "life_span": "12",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 15:08:50"
    },
    {
        "id": "28",
        "name": "Beagle",
        "weight_1": "20",
        "weight_2": "25",
        "height_1": "13",
        "height_2": "16",
        "dog_function": "trailing rabbits",
        "other_name": "English Beagle",
        "color": "Tri-color, Chocolate Tri, White & Tan, Red & White, Brown & White, Lemon & White, Orange & White",
        "location": "Great Britain",
        "animal_group": "Hound dog breeds (AKC)",
        "offsprings": "4",
        "life_span": "15",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 15:08:50"
    },
    {
        "id": "29",
        "name": "Bearded Collie",
        "weight_1": "45",
        "weight_2": "55",
        "height_1": "20",
        "height_2": "22",
        "dog_function": "sheep herding",
        "other_name": "Highland Mountain Collie, Argle Bargle, Beardie",
        "color": "Fawn, Black, Blue, Brown, Tri-color, Black & Brown",
        "location": "Scotland",
        "animal_group": "Herding dog breeds (AKC)",
        "offsprings": "4",
        "life_span": "15",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 15:08:50"
    },
    {
        "id": "30",
        "name": "Bedlington Terrier",
        "weight_1": "17",
        "weight_2": "23",
        "height_1": "15",
        "height_2": "18",
        "dog_function": "killing rat, badger, and other",
        "other_name": "Rothbury Terrier, Rodbery Terrier",
        "color": "Liver, Blue, Sandy, Liver & Tan, Blue & Tan, Sandy & Tan",
        "location": "United Kingdom",
        "animal_group": "Terrier dog breeds (AKC)",
        "offsprings": "0",
        "life_span": "14",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 15:08:50"
    },
    {
        "id": "31",
        "name": "Belgian Malinois",
        "weight_1": "60",
        "weight_2": "65",
        "height_1": "22",
        "height_2": "26",
        "dog_function": "stock herding",
        "other_name": " Mechelaar, Mechelse Scheper",
        "color": "Black-masked fawn, Black-tipped Fawn",
        "location": "Belgium",
        "animal_group": "Herding dog breeds (AKC)",
        "offsprings": "3",
        "life_span": "14",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 15:08:50"
    },
    {
        "id": "32",
        "name": "Belgian Sheepdog",
        "weight_1": "60",
        "weight_2": "65",
        "height_1": "22",
        "height_2": "26",
        "dog_function": "stock herding",
        "other_name": "Groenendael, chien de berger Belge",
        "color": "black",
        "location": "Belgium",
        "animal_group": "Herding dog breeds",
        "offsprings": "4",
        "life_span": "14",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 15:08:50"
    },
    {
        "id": "33",
        "name": "Belgian Tervuren",
        "weight_1": "60",
        "weight_2": "65",
        "height_1": "22",
        "height_2": "26",
        "dog_function": "stock herding",
        "other_name": "Chien de Berger Belge, Belgian Tervueren",
        "color": "Brindle, Black, Black & Cream, Fawn & Liver, Fawn & Black, Mahogany & Black",
        "location": "Belgium",
        "animal_group": "Herding dog breeds (AKC)",
        "offsprings": "4",
        "life_span": "14",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 15:08:50"
    },
    {
        "id": "34",
        "name": "Bernese Mountain Dog",
        "weight_1": "70",
        "weight_2": "120",
        "height_1": "23",
        "height_2": "27",
        "dog_function": "draft",
        "other_name": "Berner Sennenhund Cattle Dog, Berner",
        "color": "Tricolor (black, rust, and white)",
        "location": "Switzerland",
        "animal_group": "Working dog breeds (AKC)",
        "offsprings": "3",
        "life_span": "8",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 15:08:50"
    },
    {
        "id": "35",
        "name": "Bichon Frise",
        "weight_1": "7",
        "weight_2": "12",
        "height_1": "10",
        "height_2": "12",
        "dog_function": "companion, performer",
        "other_name": "Bichon   poil fris  Tenerife, Purebred Bichon",
        "color": "White, White & Apricot, White & Buff, White & Cream",
        "location": "Spain , Belgium,  France",
        "animal_group": "Non-Sporting dog breeds (AKC)",
        "offsprings": "2",
        "life_span": "15",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 15:08:50"
    },
    {
        "id": "36",
        "name": "Black and Tan Coonhound",
        "weight_1": "55",
        "weight_2": "75",
        "height_1": "23",
        "height_2": "27",
        "dog_function": "hunting raccoons",
        "other_name": "American Black and Tan Coonhound",
        "color": "Black & tan",
        "location": "United States",
        "animal_group": "Hound dog breeds (AKC)",
        "offsprings": "4",
        "life_span": "12",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 15:08:50"
    },
    {
        "id": "37",
        "name": "Bloodhound",
        "weight_1": "80",
        "weight_2": "110",
        "height_1": "23",
        "height_2": "27",
        "dog_function": "trailing",
        "other_name": "Chien de St.-Hubert, St. Hubert Hound",
        "color": "Red, Black & Tan, Liver & Tan",
        "location": "Belgium, France or England, Scotland",
        "animal_group": "Hound dog breeds (AKC)",
        "offsprings": "4",
        "life_span": "12",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 15:08:50"
    },
    {
        "id": "38",
        "name": "Border Collie",
        "weight_1": "30",
        "weight_2": "45",
        "height_1": "18",
        "height_2": "23",
        "dog_function": "sheep herding",
        "other_name": "Scotch Sheep Dog, Sheepdog",
        "color": "Brindle, Black, Red, Gold, Blue Merle",
        "location": "Great Britain",
        "animal_group": "Herding dog breeds (AKC)",
        "offsprings": "4",
        "life_span": "16",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 15:20:42"
    },
    {
        "id": "39",
        "name": "Border Terrier",
        "weight_1": "12",
        "weight_2": "16",
        "height_1": "10",
        "height_2": "11",
        "dog_function": "fox bolting, ratting",
        "other_name": "none",
        "color": "Red, Wheaten, Blue & Tan, Grizzle & Tan",
        "location": "Ireland, England, Great Britain, Scotland, United Kingdom, Wales",
        "animal_group": "Terrier dog breeds (AKC)",
        "offsprings": "3",
        "life_span": "15",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 15:20:42"
    },
    {
        "id": "40",
        "name": "Borzoi",
        "weight_1": "60",
        "weight_2": "105",
        "height_1": "26",
        "height_2": "28",
        "dog_function": "coursing wolves",
        "other_name": "Barzo\u00ef, Russian Wolfhound, Russkaya Psovaya Borzaya, Psovoi",
        "color": "Black, Brindle, Cream, Fawn, Red, White",
        "location": "Russia and Belarus",
        "animal_group": "Hound dog breeds (AKC)",
        "offsprings": "4",
        "life_span": "10",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 15:20:42"
    },
    {
        "id": "42",
        "name": "Bouvier des Flandres",
        "weight_1": "69",
        "weight_2": "90",
        "height_1": "24",
        "height_2": "28",
        "dog_function": "cattle herding",
        "other_name": "Flanders Cattle Dog, Vlaamse Koehond",
        "color": "Fawn, Brindle, Black, Grey, Black & Brown, Salt & Pepper",
        "location": "Belgium",
        "animal_group": "Herding dog breeds (AKC)",
        "offsprings": "3",
        "life_span": "12",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 15:20:42"
    },
    {
        "id": "43",
        "name": "Boxer",
        "weight_1": "50",
        "weight_2": "80",
        "height_1": "21",
        "height_2": "25",
        "dog_function": "bullbaiting, guardian",
        "other_name": "German Boxer, Deutscher Boxer",
        "color": "Fawn, Brindle, White",
        "location": "Germany",
        "animal_group": "Working dog breeds (AKC)",
        "offsprings": "4",
        "life_span": "12",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "0",
        "source": "0",
        "edited_date": "2015-01-29 15:20:42"
    },
    {
        "id": "44",
        "name": "Briard",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:20:42"
    },
    {
        "id": "45",
        "name": "Brittany",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:20:42"
    },
    {
        "id": "46",
        "name": "Brussels Griffon",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:20:42"
    },
    {
        "id": "47",
        "name": "Bull Terrier",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:20:42"
    },
    {
        "id": "48",
        "name": "Bulldog",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:20:42"
    },
    {
        "id": "49",
        "name": "Bullmastiff",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-01-29 15:20:42"
    },
    {
        "id": "211",
        "name": "Boston Terrier",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "212",
        "name": "Barbet",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "213",
        "name": "Basset Bleu de Gascogne",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "214",
        "name": "Basset Fauve de Bretagne",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "215",
        "name": "Bavarian Mountain Hound",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "216",
        "name": "Beauceron",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "217",
        "name": "Bergamasco",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "218",
        "name": "Berger Picard",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "219",
        "name": "Blackmouth Cur",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "220",
        "name": "Black Norwegian Elkhound",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "221",
        "name": "Black Russian Terrier",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "222",
        "name": "Blue Lacy",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "223",
        "name": "Blue Picardy Spaniel",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "224",
        "name": "Bohemian Shepherd",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "225",
        "name": "Bluetick Coonhound",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "226",
        "name": "Boerboel",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "227",
        "name": "Bouvier de Ardennes",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "228",
        "name": "Boykin Spaniel",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "229",
        "name": "Bracco Italiano",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "230",
        "name": "Braque du Bourbonnais",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "231",
        "name": "Brazilian Terrier",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "232",
        "name": "Briquet Griffon Vendeen",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "233",
        "name": "Bukovina Sheepdog",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "234",
        "name": "Bulgarian Shepherd Dog",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "235",
        "name": "Basset Artesien Normand",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "236",
        "name": "Beagle-Harrier",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },
    {
        "id": "237",
        "name": "Beaglier",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "dog_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-06 21:01:55"
    },

]

export { dogsB };