// List of goats from "k" to "z"

const goatKZ = [
  {
    "id": "52",
    "name": "Kaghani",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "53",
    "name": "Kalahari Red",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "54",
    "name": "Kamori",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "55",
    "name": "Kinder",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "56",
    "name": "Kiko",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "57",
    "name": "Kri-kri",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "58",
    "name": "Laoshan",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "59",
    "name": "Majorera",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "60",
    "name": "Maltese",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "61",
    "name": "Massif Central",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "62",
    "name": "Mini Oberhasli",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "63",
    "name": "Mountain Goat",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "64",
    "name": "Murcia-Granada",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "65",
    "name": "Murciana",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "66",
    "name": "Nigerian Dwarf",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "67",
    "name": "Nigora goat",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "68",
    "name": "Norwegian",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "69",
    "name": "Oberhasli",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "70",
    "name": "Orobica",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "71",
    "name": "Peacock",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "72",
    "name": "Philippine",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "73",
    "name": "Pygmy",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "74",
    "name": "Pygora",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "75",
    "name": "Pyrenean",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "76",
    "name": "Repartida",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "77",
    "name": "Rove",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "78",
    "name": "Russian White",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "79",
    "name": "Saanen",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "80",
    "name": "Sable Saanen",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "81",
    "name": "Sahelian",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "82",
    "name": "San Clemente Island",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "83",
    "name": "Sarda",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "84",
    "name": "Sirohi",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "85",
    "name": "Swedish Landrace",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "86",
    "name": "Somali",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "87",
    "name": "Spanish",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "88",
    "name": "Stiefelgeiss",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "89",
    "name": "Surati",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "90",
    "name": "Tauernsheck",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "91",
    "name": "Thuringian",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "92",
    "name": "Toggenburg",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "93",
    "name": "Uzbek Black",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "94",
    "name": "Valais Blackneck",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "95",
    "name": "Verata",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "96",
    "name": "West African Dwarf",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "97",
    "name": "White Shorthaired",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "98",
    "name": "Zalawadi",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "99",
    "name": "Zhongwei",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  }
];

export { goatKZ };
