// List of goats from "a" to "j"

const goatAJ = [

  {
    "id": "1",
    "name": "Alpine",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "something else",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "0",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "2",
    "name": "Altai Mountain",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "3",
    "name": "American Lamancha",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "4",
    "name": "Anatolian Black Goat",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "5",
    "name": "Anglo-Nubian",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "6",
    "name": "Angora",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "7",
    "name": "Appenzell Goat",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "8",
    "name": "Arapawa",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "9",
    "name": "Argentata of Etna",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "10",
    "name": "Australian Cashmere",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "11",
    "name": "Bagot",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "12",
    "name": "Barbari",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "13",
    "name": "Beetal",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "14",
    "name": "Belgian Fawn",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "15",
    "name": "Bilberry",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "16",
    "name": "Bionda dell'Adamello",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "17",
    "name": "Black Bengal",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "18",
    "name": "Boer",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "19",
    "name": "British Alpine",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "20",
    "name": "Canind\u00e9",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "21",
    "name": "Carpathian",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "22",
    "name": "Chyangra",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "23",
    "name": "Chamois Coloured goat",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "24",
    "name": "Changthangi",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "25",
    "name": "Charnequeira",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "26",
    "name": "Chengde Polled",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "27",
    "name": "Chengdu Brown",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "28",
    "name": "Chigu",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "29",
    "name": "Corsican",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "30",
    "name": "Dera Din Panah",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "31",
    "name": "Damascus",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "32",
    "name": "Danish Landrace",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "33",
    "name": "Don",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "34",
    "name": "Duan",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "35",
    "name": "Dutch Landrace",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "36",
    "name": "Dutch Toggenburg",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "37",
    "name": "Erzgebirge",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "38",
    "name": "Fainting",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "39",
    "name": "Garganica",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "40",
    "name": "Girgentana",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "41",
    "name": "Golden Guernsey",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "42",
    "name": "Grisons Striped",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "43",
    "name": "Hejazi",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "44",
    "name": "Hexi Cashmere",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "45",
    "name": "Huaipi",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "46",
    "name": "Hungarian Improved",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "47",
    "name": "Icelandic",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "48",
    "name": "Irish",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "49",
    "name": "Jamnapari",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "50",
    "name": "Jining Grey",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  },
  {
    "id": "51",
    "name": "Jonica",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "goat_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-15 18:38:34"
  }
];

export { goatAJ };
