// List of sheeps from "c" to "d"

const sheepsCD = [
    {
        "id": "47",
        "name": "California Red",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "48",
        "name": "California Variegated Mutant",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "49",
        "name": "Cameroon sheep",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "50",
        "name": "Campanian Barbary",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "51",
        "name": "Canadian Arcott",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "52",
        "name": "Castlemilk Moorit",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "53",
        "name": "Charmoise",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "54",
        "name": "Charollais",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "55",
        "name": "Cheviot",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "56",
        "name": "Border Cheviot",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "57",
        "name": "Brecknock Hill Cheviot",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "58",
        "name": "North Country Cheviot",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "59",
        "name": "Chios",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "60",
        "name": "Cholistani",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "61",
        "name": "Churra",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "62",
        "name": "Cikta",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "63",
        "name": "Cine Capari",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "64",
        "name": "Clun Forest",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "65",
        "name": "Coburger Fuchsschaf",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "66",
        "name": "Columbia",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "67",
        "name": "Comeback",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "68",
        "name": "Comisana",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "69",
        "name": "Coolalee",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "70",
        "name": "Coopworth",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "71",
        "name": "Cormo",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "72",
        "name": "Corriedale",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "73",
        "name": "Cotswold",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "74",
        "name": "Criollo",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "75",
        "name": "Dala Fur sheep",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "76",
        "name": "Dalesbred",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "77",
        "name": "Dagli\u00e7",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "78",
        "name": "Damani",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "79",
        "name": "Damara",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "80",
        "name": "Danish Landrace",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "81",
        "name": "Debouillet",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "82",
        "name": "Derbyshire Gritstone",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "83",
        "name": "Deutsches Bergschaf",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "84",
        "name": "Devon Closewool",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "85",
        "name": "Devon Longwoolled",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "86",
        "name": "Dohne Merino",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "87",
        "name": "Dorper",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "88",
        "name": "Dorset",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "89",
        "name": "Dorset Down",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "90",
        "name": "Drenth Heath Sheep",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "91",
        "name": "Drysdale",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    }
];
export { sheepsCD };
