// List of sheeps from "l" to "r"

const sheepsLR = [
    {
        "id": "137",
        "name": "Lacaune",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "138",
        "name": "Latxa",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "139",
        "name": "Lincoln",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "140",
        "name": "Lithuanian Black-headed",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "141",
        "name": "Llanwenog",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "142",
        "name": "Lleyn",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "143",
        "name": "Lohi",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "144",
        "name": "Lonk",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "145",
        "name": "Marwari",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "146",
        "name": "Manx Loaghtan",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "147",
        "name": "Massese sheep",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "148",
        "name": "Meatmaster",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "149",
        "name": "Mehraban",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "150",
        "name": "Merinizzata Italiana",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "151",
        "name": "Merino",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "152",
        "name": "Booroola Merino",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "153",
        "name": "Delaine Merino",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "154",
        "name": "Merinolandschaf",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "155",
        "name": "Poll Merino",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "156",
        "name": "South African Meat Merino",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "157",
        "name": "Montadale",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "158",
        "name": "Morada Nova",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "159",
        "name": "Najdi",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "160",
        "name": "Namaqua Afrikaner",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "161",
        "name": "Nali",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "162",
        "name": "Navajo-Churro sheep",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "163",
        "name": "Newfoundland",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "164",
        "name": "Nilgiri",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "165",
        "name": "Noire du Velay",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "166",
        "name": "Norfolk Horn",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "167",
        "name": "North Ronaldsay",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "168",
        "name": "Northern European short-tailed sheep",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "169",
        "name": "Ouessant",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "170",
        "name": "Oxford",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "171",
        "name": "Panama",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "172",
        "name": "Pedi sheep",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "173",
        "name": "Pelib\u00fcey",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "174",
        "name": "Perendale",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "175",
        "name": "Pinzirita",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "176",
        "name": "Polwarth",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "177",
        "name": "Polypay",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "178",
        "name": "Portland",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "179",
        "name": "Priangan",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "180",
        "name": "Poll Dorset",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "181",
        "name": "Polled Dorset",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "182",
        "name": "Pomeranian Coarsewool Sheep",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "183",
        "name": "Racka",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "184",
        "name": "Rambouillet",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "185",
        "name": "Red Maasai",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "186",
        "name": "Rideau Arcott",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "187",
        "name": "Romanov",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "188",
        "name": "Romney sheep",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "189",
        "name": "Roslag",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "190",
        "name": "Rouge de l'Ouest",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "191",
        "name": "Rough Fell",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "192",
        "name": "Royal White",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "193",
        "name": "Ruda",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "194",
        "name": "Rya",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    },
    {
        "id": "195",
        "name": "Ryeland",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "sheep_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 22:13:20"
    }
];

export { sheepsLR };
