// List of pigs from "s" to "z"

const sheepsSZ = [
  
  {
    "id": "196",
    "name": "Sakiz",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "197",
    "name": "Santa Cruz",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "198",
    "name": "Santa In\u00eas",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "199",
    "name": "Sardinian",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "200",
    "name": "Scottish Blackface",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "201",
    "name": "Scottish Dunface",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "202",
    "name": "Serrai",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "203",
    "name": "Shetland",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "204",
    "name": "Shropshire",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "205",
    "name": "Skudde",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "206",
    "name": "Soay",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "207",
    "name": "Somali",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "208",
    "name": "Sopravissana",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "209",
    "name": "Southdown",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "210",
    "name": "Sp\u00e6lsau",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "211",
    "name": "St. Croix",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "212",
    "name": "Suffolk",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "213",
    "name": "Swaledale",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "214",
    "name": "Taleshi",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "215",
    "name": "Targhee",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "216",
    "name": "Teeswater",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "217",
    "name": "Texel",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "218",
    "name": "Tiroler Steinschaf",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "219",
    "name": "Tunis",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "220",
    "name": "Uda",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "221",
    "name": "Valais Blacknose",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "222",
    "name": "Van Rooy",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "223",
    "name": "Vend\u00e9en",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "224",
    "name": "Waziri",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "225",
    "name": "Welsh Mountain sheep",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "226",
    "name": "Badger Face Welsh Mountain",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "227",
    "name": "Balwen Welsh Mountain sheep",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "228",
    "name": "Black Welsh Mountain sheep",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "229",
    "name": "Wensleydale",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "230",
    "name": "West African Dwarf",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "231",
    "name": "White Suffolk",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "232",
    "name": "Whiteface Dartmoor",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "233",
    "name": "Whitefaced Woodland",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "234",
    "name": "Wiltipoll",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "235",
    "name": "Wiltshire Horn",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "236",
    "name": "Zelazna",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  },
  {
    "id": "237",
    "name": "Zwartbles",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "sheep_function": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-05-12 22:13:20"
  }
]
export { sheepsSZ };
