// List of ponies from "g" to "z"

const poniesGZ = [
    {
        "id": "32",
        "name": "Galician Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "33",
        "name": "Garrano",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "34",
        "name": "Gayoe",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "35",
        "name": "German Riding Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "36",
        "name": "Gotland Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "37",
        "name": "Guizhou pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "38",
        "name": "Hackney pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "39",
        "name": "Hokkaido Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "40",
        "name": "Hucul Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "41",
        "name": "Indian Country Bred",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "42",
        "name": "Java Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "43",
        "name": "Kerry bog pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "44",
        "name": "Landais Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "45",
        "name": "Lijiang pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "46",
        "name": "Lundy Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "47",
        "name": "Manipuri Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "48",
        "name": "Miyako Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "49",
        "name": "Narym Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "50",
        "name": "New Forest Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "51",
        "name": "Newfoundland pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "52",
        "name": "Noma pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "53",
        "name": "Nooitgedacht pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "54",
        "name": "Ob pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "55",
        "name": "Peneia Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "56",
        "name": "Petiso Argentino",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "57",
        "name": "Pindos Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "58",
        "name": "Poney Mousseye",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "59",
        "name": "Pony of the Americas",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "60",
        "name": "Pottok",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "61",
        "name": "Quarter pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "62",
        "name": "Sable Island Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "63",
        "name": "Sandalwood Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "64",
        "name": "Shetland pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "65",
        "name": "Skyros Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "66",
        "name": "Sumba and Sumbawa Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "67",
        "name": "Tibetan Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "68",
        "name": "Timor Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "69",
        "name": "Tokara Pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "70",
        "name": "Vyatka horse",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "71",
        "name": "Welara",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "72",
        "name": "Welsh pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "73",
        "name": "Zaniskari pony",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    },
    {
        "id": "74",
        "name": "\u017demaitukas",
        "weight_1": "0",
        "weight_2": "0",
        "height_1": "0",
        "height_2": "0",
        "pony_function": "",
        "other_name": "",
        "color": "",
        "location": "",
        "animal_group": "",
        "offsprings": "0",
        "life_span": "0",
        "section_id": "8",
        "specie_id": "1",
        "sub_specie_id": "17",
        "description": "",
        "source": "",
        "edited_date": "2015-05-12 20:10:23"
    }
];

export { poniesGZ };