// List of cats from "c" to "k"
// This list does not include big cats

let catsCK = [
  {
    "id": "11",
    "name": "Chartreux",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "coat": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-02-13 21:14:18"
  },
  {
    "id": "12",
    "name": "Cornish Rex",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "coat": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-02-13 21:14:18"
  },
  {
    "id": "13",
    "name": "Cymric",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "coat": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-02-13 21:14:18"
  },
  {
    "id": "14",
    "name": "Devon Rex",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "coat": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-02-13 21:14:18"
  },
  {
    "id": "15",
    "name": "Egyptian Mau",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "coat": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-02-13 21:14:18"
  },
  {
    "id": "16",
    "name": "Exotic Shorthair",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "coat": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-02-13 21:14:18"
  },
  {
    "id": "17",
    "name": "Havana Brown",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "coat": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-02-13 21:14:18"
  },
  {
    "id": "18",
    "name": "Himalayan",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "coat": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-02-13 21:14:18"
  },
  {
    "id": "19",
    "name": "Japanese Bobtail",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "coat": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-02-13 21:14:18"
  },
  {
    "id": "20",
    "name": "Javanese",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "coat": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-02-13 21:14:18"
    }
]
export { catsCK };