// List of cats from "l" to "r"
// This list does not include big cats

let catsLR = [
  {
    "id": "22",
    "name": "Maine Coon",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "coat": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-02-13 21:14:18"
  },
  {
    "id": "23",
    "name": "Manx",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "coat": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-02-13 21:14:18"
  },
  {
    "id": "24",
    "name": "Munchkin",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "coat": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-02-13 21:14:18"
  },
  {
    "id": "25",
    "name": "Nebelung",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "coat": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-02-13 21:14:18"
  },
  {
    "id": "26",
    "name": "Norwegian Forest Cat",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "coat": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-02-13 21:14:18"
  },
  {
    "id": "27",
    "name": "Ocicat",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "coat": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-02-13 21:14:18"
  },
  {
    "id": "28",
    "name": "Oriental",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "coat": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-02-13 21:14:18"
  },
  {
    "id": "29",
    "name": "Persian",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "coat": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-02-13 21:14:18"
  },
  {
    "id": "30",
    "name": "Ragdoll",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "coat": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-02-13 21:14:18"
  },
  {
    "id": "31",
    "name": "Russian Blue",
    "weight_1": "0",
    "weight_2": "0",
    "height_1": "0",
    "height_2": "0",
    "coat": "",
    "other_name": "",
    "color": "",
    "location": "",
    "animal_group": "",
    "offsprings": "0",
    "life_span": "0",
    "section_id": "8",
    "specie_id": "1",
    "sub_specie_id": "17",
    "description": "",
    "source": "",
    "edited_date": "2015-02-13 21:14:18"
  }
]

export { catsLR };